# Generated by Django 4.2.7 on 2023-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('math_question', models.CharField(blank=True, max_length=255, null=True)),
                ('riddle_question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.IntegerField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('image_question', models.ImageField(blank=True, null=True, upload_to='level_images/')),
                ('riddle_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('question_orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=10)),
            ],
        ),
    ]
